[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "netquery"
version = "0.1.0"
dependencies = ["netmiko", "typer", "tabulate", "pandas"]

[project.scripts]
netquery = "netquery.main:app"
