class NetqueryException(Exception): ...


class NetqueryTimeoutException(NetqueryException): ...


class NetqueryUnknownDeviceTypeException(NetqueryException): ...


class NetqueryUnauthorizedException(NetqueryException): ...


class NetqueryNoMatchesException(NetqueryException): ...
